/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package huvudsidaA;

import javax.swing.JOptionPane;

/**
 *
 * @author elina
 */
public class RegistreraAlien extends javax.swing.JFrame {

    /**
     * Creates new form RegistreraUtrustning
     */
    public RegistreraAlien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alienPanel = new javax.swing.JPanel();
        alienLbl = new javax.swing.JLabel();
        datumTxt = new javax.swing.JTextField();
        namnTxt = new javax.swing.JTextField();
        losenordTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        platsTxt = new javax.swing.JTextField();
        agentTxt = new javax.swing.JTextField();
        registrerabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alienPanel.setBackground(new java.awt.Color(171, 189, 219));

        alienLbl.setText("Registrera ny alien");

        datumTxt.setText("Datum");
        datumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumTxtActionPerformed(evt);
            }
        });

        namnTxt.setText("Namn");
        namnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnTxtActionPerformed(evt);
            }
        });

        losenordTxt.setText("Lösenord");
        losenordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenordTxtActionPerformed(evt);
            }
        });

        telTxt.setText("Telefonnummer");
        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        platsTxt.setText("Plats");
        platsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platsTxtActionPerformed(evt);
            }
        });

        agentTxt.setText("Ansvarig agent");
        agentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentTxtActionPerformed(evt);
            }
        });

        registrerabtn.setText("Registrera");
        registrerabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrerabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alienPanelLayout = new javax.swing.GroupLayout(alienPanel);
        alienPanel.setLayout(alienPanelLayout);
        alienPanelLayout.setHorizontalGroup(
            alienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alienPanelLayout.createSequentialGroup()
                .addGroup(alienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(alienLbl))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(namnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(losenordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(platsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alienPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(agentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alienPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registrerabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alienPanelLayout.setVerticalGroup(
            alienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alienPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(alienLbl)
                .addGap(59, 59, 59)
                .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(losenordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(platsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registrerabtn)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(alienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(alienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumTxtActionPerformed

    private void namnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnTxtActionPerformed

    private void losenordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenordTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void platsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platsTxtActionPerformed

    private void agentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentTxtActionPerformed

    private void registrerabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrerabtnActionPerformed
        try {
            String datum = datumTxt.getText();
            String password = losenordTxt.getText();
            String namn = namnTxt.getText();
            String telefon = telTxt.getText();
            String plats = platsTxt.getText();
            String agent = agentTxt.getText();
           //losenord.validateLosen(user, password);
//            String namnfraga = "SELECT NAMN from AGENT where NAMN like '" + user + "'";
//            String losenfraga = "SELECT LOSENORD from AGENT where NAMN like '" + user + "'";
//            String hamtadeNamnet = idb.fetchSingle(namnfraga);
//            String hamtadeLosen = idb.fetchSingle(losenfraga);
//           
//               if (user.isBlank() ) 
//               { //denna kollar om rutan är tom
//                JOptionPane.showMessageDialog(null, "alla fällt måste vara ifyllda");
//               
//            }
//
//            if (user.isBlank() ) { //denna kollar om rutan är tom
//                JOptionPane.showMessageDialog(null, "alla fällt måste vara ifyllda");
//           
//            }
//
//            if(user.equals(hamtadeNamnet))
//            {
//            if (hamtadeLosen.equals(password))//kollar så
//            {
//                System.out.println("det funkade");
//                  viewHuvudSida.setVisible(true);
//                  this.setVisible(false);
//               
//            } 
//            else //check vid fealktigt lösenord av användaren
//            {
//                System.out.println(password+ " " + hamtadeLosen);
//                System.out.println("felaktigt lösenord ");
//           }
//            }
//            else
//            {
//                System.out.println("Felaktigt användarnamn");
//            }

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internet felmeddelande" + e.getMessage());
        }
    }//GEN-LAST:event_registrerabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreraAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agentTxt;
    private javax.swing.JLabel alienLbl;
    private javax.swing.JPanel alienPanel;
    private javax.swing.JTextField datumTxt;
    private javax.swing.JTextField losenordTxt;
    private javax.swing.JTextField namnTxt;
    private javax.swing.JTextField platsTxt;
    private javax.swing.JButton registrerabtn;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
